//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jpeg2000Filetype.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jpeg2000Filetype.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error decoding image..
        /// </summary>
        internal static string DecodeFailure {
            get {
                return ResourceManager.GetString("DecodeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encoding image..
        /// </summary>
        internal static string EncodeFailure {
            get {
                return ResourceManager.GetString("EncodeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing image data..
        /// </summary>
        internal static string ImageBufferWrite {
            get {
                return ResourceManager.GetString("ImageBufferWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jasper initilization failed..
        /// </summary>
        internal static string InitFailed {
            get {
                return ResourceManager.GetString("InitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of memory..
        /// </summary>
        internal static string OutOfMemory {
            get {
                return ResourceManager.GetString("OutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert to sRGB..
        /// </summary>
        internal static string ProfileConversion {
            get {
                return ResourceManager.GetString("ProfileConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create color profile..
        /// </summary>
        internal static string ProfileCreation {
            get {
                return ResourceManager.GetString("ProfileCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many channels..
        /// </summary>
        internal static string TooManyComponets {
            get {
                return ResourceManager.GetString("TooManyComponets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown image format..
        /// </summary>
        internal static string UnknownFormat {
            get {
                return ResourceManager.GetString("UnknownFormat", resourceCulture);
            }
        }
    }
}
